// This file is generated by Ember Desktop.  Please do not edit manually.
//
//



#include "app/framework/include/af.h"
#include "app/framework/cli/custom-cli.h"


EmberCommandEntry emberCommandTable[] = {
  CUSTOM_COMMANDS
  emberCommandEntryTerminator()
};



